<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlug($slug)
    {
    	$query = $this->createQueryBuilder('a')
    	->Where('a.slug = :arg')
    	->setParameter('arg', $slug)
    	->getQuery();
    
    	return $query->getOneOrNullResult();
    }
}
