<?php

namespace AppBundle\Repository;

/**
 * ProjectImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectImageRepository extends \Doctrine\ORM\EntityRepository
{
}
