app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/api_routes.yml"

sonata_api_media:
    type:         rest
    prefix:       /media-api
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
