services:
    app.admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, PixSortableBehaviorBundle:SortableAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: Clients}
        calls:
            - [ setPositionService, ["@pix_sortable_behavior.position"]]

    app.admin.project_type:
        class: AppBundle\Admin\ProjectTypeAdmin
        arguments: [~, AppBundle\Entity\ProjectType, PixSortableBehaviorBundle:SortableAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: "Project Types"}
        calls:
            - [ setPositionService, ["@pix_sortable_behavior.position"]]

    app.admin.project:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, PixSortableBehaviorBundle:SortableAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: Projects}
        calls:
            - [ setPositionService, ["@pix_sortable_behavior.position"]]

    app.admin.project_image:
        class: AppBundle\Admin\ProjectImageAdmin
        arguments: [~, AppBundle\Entity\ProjectImage, PixSortableBehaviorBundle:SortableAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: "Project Images"}

    app.admin.skill:
        class: AppBundle\Admin\SkillAdmin
        arguments: [~, AppBundle\Entity\Skill, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: "Skills"}

    app.admin.tag:
        class: AppBundle\Admin\TagAdmin
        arguments: [~, AppBundle\Entity\Tag, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: "Tags"}

    app.admin.metadata:
        class: AppBundle\Admin\MetadataAdmin
        arguments: [~, AppBundle\Entity\Metadata, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: "Metadata"}

    app.admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Page, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Lead-Web", label: "Pages"}
