services:
    app.admin.project:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Project}

    app.admin.project_type:
        class: AppBundle\Admin\ProjectTypeAdmin
        arguments: [~, AppBundle\Entity\ProjectType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ProjectType}

    app.admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Client}

    app.admin.project_image:
        class: AppBundle\Admin\ProjectImageAdmin
        arguments: [~, AppBundle\Entity\ProjectImage, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ProjectImage}
